#H2 \uba54\ubaa8\ub9ac \ub370\uc774\ud130\ubca0\uc774\uc2a4\uc778 testdb \ub97c \uc0dd\uc131\ud558\ub294 \ucf54\ub529
spring.datasource.hikari.jdbc-url=jdbc:h2:mem:testdb;MODE=MYSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#H2 \uba54\ubaa8\ub9ac DB\uc5d0 \ucd08\uae30 \uc0ac\uc6a9\uc790 \uac12 \ucd94\uac00 https://khdscor.tistory.com/4
spring.jpa.defer-datasource-initialization=true
spring.datasource.schema=classpath:import_h2db_only.sql